refactor(input): change input
Medical-Information/medical-information-frontend pull request #101
Opened 2023-07-24 19:43 UTC by AleksandrDronov

2023-07-24 20:57 UTC, elrouss requested changes
Описание компонента инпута - одна из самых сложных (и противных) работ. Герой тот, кто за него берется. Я посмотрел поверхностно, вроде бы получилось неплохо, но есть несколько замечаний. Что-то, скорее всего, буду править уже по ходу верстки формы и написания валидации.

2023-07-24 20:57 UTC, elrouss commented on src/shared/input/input.tsx
> +import React, { useCallback, useMemo, useRef, useState } from 'react';
Я думаю, что здесь мемоизация в принципе не нужна: компонент иконки с глазом и проч. настолько малы, что их ререндер особо не влияет на производительность приложения. Кроме того, они у тебя вроде бы все равно продолжают перерендериваться

2023-07-24 20:57 UTC, elrouss commented on src/shared/input/input.tsx
> +          <Icon
Иконку с глазом лучше завернуть в тег `button`, добавить `aria-label` для скринридеров (Показать пароль/Скрыть пароль), который будет меняться в зависимости от состояния иконки. Тогда иконка будет в том числе получать фокус при навигации клавишами и будет понятно, что она интерактивна

2023-07-24 20:57 UTC, elrouss commented on src/shared/input/input.module.scss
>    width: 480px;
Не указывать жестко ширину. Воспользоваться `max-width`. Замечу, что по макету максимальная ширина равняется `544px`. Я еще часто использую прием `width: 100%`, что делает инпут гибким под контейнер. Но здесь, вероятно, будет достаточно `max-width: 544px`

Также обратил внимание, что задана жесткая высота у поля с ошибкой: `16px`. Лучше задать `min-height` (тем более, что есть ошибки в 2 строки, где высота - 32px)

2023-07-24 20:57 UTC, elrouss commented on src/shared/input/input.tsx
> +            icon={visible ? 'EyeIcon' : 'EyeClosedIcon'}
Еще в стилях где-то надо добавить `8px` отступа между текстовым полем и глазом: сейчас максимальный текст прижимается к иконке 
<img width="191" alt="Снимок экрана 2023-07-24 в 23 38 47" src="https://github.com/Medical-Information/medical-information-frontend/assets/108838349/081bf6d7-9a28-47ef-9ff9-b230f5be4638">

2023-07-24 20:57 UTC, elrouss commented on src/shared/input/input.stories.tsx
>  export const SuccessMedium: TStory = {
Все, что с success в storybook, поставь у глаза дефолтный false, чтобы он не отрисовывался

2023-07-24 20:57 UTC, elrouss commented on src/shared/input/input.tsx
> +  isDisabled?: boolean;
По идее, в disabled глаз тоже должен быть серым и неинтерактивным

2023-07-24 20:57 UTC, elrouss commented on src/shared/input/input.module.scss
По макету, каретка должна иметь цвет `$color-brand-primary-900`

2023-07-24 20:57 UTC, elrouss commented on src/shared/input/input.tsx
>    errorText?: string;
На валидации этот пропс, скорее всего, уйдет: пока оставляем

2023-07-25 05:36 UTC, AleksandrDronov commented on src/shared/input/input.tsx
> +import React, { useCallback, useMemo, useRef, useState } from 'react';
Брал с эталонного инпута). Можно подумать в будущем.

2023-07-25 05:37 UTC, AleksandrDronov commented on src/shared/input/input.tsx
> +          <Icon
Дельный совет

2023-07-25 05:57 UTC, AleksandrDronov commented on src/shared/input/input.module.scss
>    width: 480px;
Тоже обычно делаю 100%. Исправлю. Через extraClass можно задать любую ширину.

2023-07-25 10:00 UTC, merged