Feat/entry business logic
Medical-Information/medical-information-frontend pull request #130
Opened 2023-07-30 13:48 UTC by elrouss

1) Доверстал формы регистрации и авторизации, сверил с Pixel Perfect и W3C;
2) Сделал валидацию форм;
3) Реализовал логику регистрации и авторизации с обработкой ошибок от сервера;
4) Сохраняю токен при авторизации в локальном хранилище

P.S. Sorry за `any`

2023-07-30 20:19 UTC, bofeof reviewed
вопрос хранения данных без прямого обращения к local storage - беру пока на подумать, мне надо самой воспроизвести это в коде, комментарии по этой теме не писала пока

2023-07-30 20:48 UTC, elrouss commented on src/services/features/user/slice.tsx
> +      .addDefaultCase((state) => state);
В доке написано, что можно делать: я оставляю для дефолтных кейсов

2023-07-30 20:48 UTC, elrouss commented on src/services/features/user/slice.tsx
> +        // TODO: по идее, бэки должны посылать имя и фамилию юзера для сохранения в store и отображения в лк
Это следующий этап, когда появится личный кабинет

2023-07-30 20:52 UTC, elrouss commented on src/services/features/user/slice.tsx
> +    error: null | any; // TODO: коллеги, если подправите тип, буду признателен. Устал бороться с TS >_<
Не сработает, потому что в `error` оказывается объект с ключом и значением в виде массива строк (`[key: string]: string` - тоже не работает)

2023-07-30 20:53 UTC, elrouss commented on src/services/features/user/api.tsx
> +      return rejectWithValue(err);
Я видел такое у тебя. Есть пример из доки?

2023-07-30 20:54 UTC, elrouss commented on src/services/features/user/api.tsx
> +        return rejectWithValue(resBody);
Увы, с `throw` не работало. Выбрасывало дефолтную ошибку, в `rejectWithValue` оказывается `payload` пустым. Это единственное решение, которое заработало, как нужно

2023-07-30 20:58 UTC, bofeof commented on src/services/features/user/api.tsx
> +        return rejectWithValue(resBody);
так тебе надо завести ошибку через стандартный new Error, передай внутри ошибки нужные ключи, в catch она красиво обработается как надо

2023-07-30 20:59 UTC, bofeof commented on src/services/features/user/api.tsx
> +      return rejectWithValue(err);
в доке редакс не будет, это общая практика

2023-07-30 21:01 UTC, elrouss commented on src/pages/sign-in/sign-in.module.scss
>  .inputs {
Я думал об этом, но макетом, к сожалению заложен отступ ровно в `32px` (учитывай, что нужны еще пара пикселей для отступа от нижнего края ошибки до верхнего края следующего инпута, т. е. условно - `36px`). Сейчас у ребят при возникновении ошибки в 2 строчки предусмотрен отступ в `12px` от ошибки до инпута

2023-07-30 21:02 UTC, elrouss commented on src/pages/sign-up/sign-up.module.scss
>    row-gap: 12px;
Я думал об этом, но макетом, к сожалению заложен отступ ровно в `32px` (учитывай, что нужны еще пара пикселей для отступа от нижнего края ошибки до верхнего края следующего инпута, т. е. условно - `36px`). Сейчас у ребят при возникновении ошибки в 2 строчки предусмотрен отступ в `12px` от ошибки до инпута

2023-07-30 21:04 UTC, elrouss commented
К общему комментарию
"вопрос хранения данных без прямого обращения к local storage - беру пока на подумать, мне надо самой воспроизвести это в коде, комментарии по этой теме не писала пока"

Я предлагаю пока задуматься над фильтрами (это будет жесть), добавлением в избранное либо прокруткой новостей/статей по кнопке "Еще" (учитывая курсорную пагинацию), когда до deadline остается 3 недели. Тонкости - в начале на финальном этапе работы. Сейчас главное, чтобы заработала основная логика сайта (+ у нас еще нет адаптива)

2023-07-30 21:05 UTC, bofeof commented on src/services/features/user/slice.tsx
> +        // TODO: по идее, бэки должны посылать имя и фамилию юзера для сохранения в store и отображения в лк
тебе тут не нужен личный кабинет, ты уже можешь логиниться и токен, auth_token сохранять, тебе нужно его просто отправить в другом запросе и все

2023-07-30 21:06 UTC, elrouss commented on src/services/features/user/slice.tsx
> +        // TODO: по идее, бэки должны посылать имя и фамилию юзера для сохранения в store и отображения в лк
Оставляем до личного кабинета, иначе этот ПР никогда не закроется

2023-07-30 21:15 UTC, bofeof commented on src/pages/sign-in/sign-in.module.scss
>  .inputs {
ну тут с высотой нужно поиграть, можно сделать span в 30px, gap убрать) вид не изменится у форм, зато дергаться не будет
вот смотри, есть небольшой отступ между input и span
<img width="380" alt="image" src="https://github.com/Medical-Information/medical-information-frontend/assets/76571113/d9a3c714-ea34-440d-8f3e-6adcfaba77b5">

2023-07-30 21:17 UTC, elrouss commented on src/pages/sign-in/sign-in.module.scss
>  .inputs {
<img width="521" alt="Снимок экрана 2023-07-31 в 00 16 57" src="https://github.com/Medical-Information/medical-information-frontend/assets/108838349/c166cc60-dc1d-4b99-8254-f2219f94fd86">

По макету - должно быть `12px`

2023-07-30 21:19 UTC, elrouss commented on src/services/features/user/api.tsx
> +        return rejectWithValue(resBody);
<img width="325" alt="Снимок экрана 2023-07-31 в 00 19 12" src="https://github.com/Medical-Information/medical-information-frontend/assets/108838349/b63d74ef-a8cb-4d8f-808c-0336d3644503">

Делал по-всякому: не работает

2023-07-30 21:21 UTC, elrouss commented on src/services/features/user/api.tsx
> +        return rejectWithValue(resBody);
А, стоп. Кажется, нашел)

2023-07-30 23:26 UTC, elrouss commented on src/services/features/user/api.tsx
> +        return rejectWithValue(resBody);
Поправил

2023-07-31 01:11 UTC, elrouss commented on src/services/features/user/slice.tsx
> +        // TODO: по идее, бэки должны посылать имя и фамилию юзера для сохранения в store и отображения в лк
Реализовал)

2023-07-31 10:09 UTC, AleksandrDronov requested changes
В целом всё круто. Хорошая верстка, хорошая валидация, чистый код.
Что нужно поправить. 
1. Типизация. Посмотри ролик непомнящего.
2. Инпут. В инпунт могут приходит данные только через пропсы. Внутри shared компоненты мы не можем обращаться к стейту. 

Комментарии по коду ниже

2023-07-31 10:09 UTC, AleksandrDronov commented on src/services/features/user/slice.tsx
> +    error: null | any; // TODO: коллеги, если подправите тип, буду признателен. Устал бороться с TS >_<
Сработает если payload затипизируешь.  { [name: string] : string }

2023-07-31 10:10 UTC, AleksandrDronov commented on src/pages/sign-up/sign-up.module.scss
>    row-gap: 12px;
Оставляем с раздвижкой, если дизайнеры так хотят и уведомлены, что форма чуть раздвигается при появлениии ошибки.

2023-07-31 10:13 UTC, elrouss commented on src/services/features/user/api.tsx
> +      return rejectWithValue(err);
Этот кусок кода переработан мной в одном из двух последних коммитов

2023-07-31 10:13 UTC, elrouss commented on src/utils/data/validation/yup-schema.tsx
> +    .matches(regexEmail, validationErrors.user.email.acceptableSymbols)
Да, согласен. Забыл поправить

2023-07-31 12:55 UTC, AleksandrDronov commented on src/services/features/user/slice.tsx
> +    error: null | any; // TODO: коллеги, если подправите тип, буду признателен. Устал бороться с TS >_<
Я ж гворю не работает потому что payload не типизирован

2023-08-01 17:41 UTC, elrouss commented
1) Поправил регулярные выражения;
2) Поднял пропсы из компонента инпута, сделав его универсальным;
3) Затипизировал Redux

2023-08-01 19:34 UTC, AleksandrDronov approved these changes

2023-08-01 21:20 UTC, merged