Pages/profile
Medical-Information/medical-information-frontend pull request #144
Opened 2023-08-02 10:24 UTC by AleksandrDronov

Верстка без валидации формы и связи с беком.

2023-08-02 15:47 UTC, elrouss requested changes
Хорошая и аккуратная верстка, соблюдена семантика. Молодец!

Есть несколько замечаний, которые отметил по коду. Также обрати внимание на отступы в панели навигации: из-за паддингов можно кликнуть на блок, который заезжает в меняющийся контейнер

<img width="343" alt="Снимок экрана 2023-08-02 в 18 44 22" src="https://github.com/Medical-Information/medical-information-frontend/assets/108838349/33a7b821-7f21-4688-a88c-ca5f45066767">

2023-08-02 15:47 UTC, elrouss commented on src/App.tsx
> -  }, []);
`dispatch` можно не добавлять в массив зависимостей `useEffect`: это ошибка линтера, который не знает особенности работы с `dispatch`. Можно, по идее, установить специальное расширение и в нем прописать дополнительные правила для этого и других похожих случаев

2023-08-02 15:47 UTC, elrouss commented on src/components/sidebar/sidebar.module.scss
> +    letter-spacing: 0.4px;
Можно использовать переменную `$font-letter-spacing-main`

2023-08-02 15:47 UTC, elrouss commented on src/components/sidebar/sidebar.module.scss
> +    letter-spacing: 0.4px;
Можно использовать переменную `$font-letter-spacing-main`

2023-08-02 15:47 UTC, elrouss commented on src/components/sidebar/sidebar.module.scss
> +    letter-spacing: 0.4px;
Можно использовать переменную `$font-letter-spacing-main`

2023-08-02 15:47 UTC, elrouss commented on src/components/sidebar/sidebar.module.scss
> +    letter-spacing: 0.4px;
Можно использовать переменную `$font-letter-spacing-main`

2023-08-02 15:47 UTC, elrouss commented on src/components/sidebar/sidebar.tsx
> +      <ul className={styles.sidebar_list}>
Для семантики лучше дополнительно обернуть таблицу в тег `nav`

2023-08-02 15:47 UTC, elrouss commented on src/components/sidebar/sidebar.tsx
> +        <li className={styles.sidebar_list_item}>
Давай данные вынесем в список и отрисуем с помощью `map`? Получится изящнее, без трехкратного дублирования кода

2023-08-02 15:47 UTC, elrouss commented on src/components/sidebar/sidebar.tsx
> +        <p className={styles.sidebar_label}>Подписаться на рассылку</p>
Слетела верстка: сейчас нужно лейбл не прокидывать внутрь чекбокса, а ставить рядом - все оборачивать в контейнер и выравнивать с помощью `flexbox`.

Я думаю, что это нужно в целом обернуть в `form` и по клику на чекбокс делать запрос к серверу (дизайнеры должны прописать состояния для успеха/неуспеха операции).

Можешь сейчас этого не делать -> я подправлю

2023-08-02 15:47 UTC, elrouss commented on src/components/user-profile/user-profile.tsx
> +            администратору: admin@stethoscope-portal.ru
Сейчас ребята внесли по моей просьбе дополнение: email нужно обернуть в `a` с `mailto:` и почтовым адресом в `href` и прописать стили (для `:hover` и `:active` можешь взять стили ссылок из подвала - там точно такие же)

2023-08-02 15:47 UTC, elrouss commented on src/pages/profile/profile-page.tsx
> +        <Routes>
Смущает этот момент: разве мы можем вкладывать `Routes` в `Routes` (с учетом корневого компонента)? Здесь уместно использовать `Outlet`

2023-08-02 15:47 UTC, elrouss commented on src/pages/sign-in/sign-in.tsx
> -  }, []);
Не надо закидывать это все в `useEffect`, следуя подсказке eslint! Она неправильная -> у меня логика ломается с отрисовкой ошибок из сервера

2023-08-03 10:41 UTC, AleksandrDronov commented on src/components/sidebar/sidebar.tsx
> +        <li className={styles.sidebar_list_item}>
Потом отрефакторим. Сейчас в мыле.

2023-08-03 10:41 UTC, AleksandrDronov commented on src/components/sidebar/sidebar.tsx
> +        <p className={styles.sidebar_label}>Подписаться на рассылку</p>
Оставляю тебе)

2023-08-03 10:54 UTC, AleksandrDronov commented on src/pages/profile/profile-page.tsx
> +        <Routes>
Слушай не знаю. Так делал неоднократно. Вопросов и претензий не получал. Твой вариант преподчительнее конечно. Он в доке прописан. Предлагаю оставить на потом. Так как всё работает.

2023-08-03 12:28 UTC, elrouss approved these changes
Вроде бы все нормально, молодец) нейминг хороший

Обрати все же внимание на map с табами: получится изящно и не будет дублирования кода (id при отрисовке можно генерировать автоматически с помощью `nanoid`)

2023-08-03 12:28 UTC, elrouss commented on src/components/sidebar/sidebar.tsx
> +          <li className={styles.sidebar_list_item}>
Не отрисовал через `map`: очень жаль. Если в перспективе добавятся еще табы, то придется копировать структуру каждого элемента и вручную вставлять (не говоря о том, что если html-структура одного таба изменится - придется менять все). А так бы дописывал только роут и label

2023-08-03 12:28 UTC, elrouss commented on src/pages/profile/profile-page.tsx
> +        <Routes>
Угу, в консоли вроде ошибок нет. Просто мне казалось, что раньше в корне React ругался, если вкладывать Routes в Routes (но, может, с чем-то другим путаю).

Посмотрим в общем

2023-08-03 12:28 UTC, elrouss commented on src/utils/routes.ts
> +  favorites: 'favorites',
Без слэша в начале?

2023-08-03 13:37 UTC, AleksandrDronov commented on src/utils/routes.ts
> +  favorites: 'favorites',
Да, это спецом. Со слешм и без по-ращному работают

2023-08-03 13:37 UTC, merged