Feat/filter modal
Medical-Information/medical-information-frontend pull request #168
Opened 2023-08-09 16:16 UTC by AleksandrDronov

Сделал фильтрацию в модалке.
Пока код такой себе. Работает, но повторяется

2023-08-09 22:11 UTC, bofeof reviewed
Логика фильтров в модальном окне отрабатывает как нужно: у меня получается увидеть результат фильтрации, а также сбросить фильтры при необходимости. Есть пара моментов, которые смущают, предлагаю над этим подумать и поправить функционал:

1. Когда выбрали фильтры и переоткрыли модальное окно, ранее выбранные фильтры сбрасываются, хотя отфильтрованные данные мы по-прежнему видим по статьям. По идее, состояние выбранных фильтров должно сохраняться до тех пор, пока пользователь сам их не сбросит или не перезагрузит окно.
2. Если фильтры из модального окна должны дополнять фильтры из карусели, расширять поиск, то сейчас они друг друга перезатирают и результат получается либо по модальным фильтрам, либо карусель.

По стилям:
1. Не хватает бордера в 1px над кнопками "показать" "очистить все":
<img width="517" alt="image" src="https://github.com/Medical-Information/medical-information-frontend/assets/76571113/e56d28e8-3304-4f06-bea2-d94c567725b6">

2. Очень не хватает плавного открытия и закрытия попапа

3. Предлагаю окно с фильтрами вытащить в центр экрана, чтобы оно всегда было у пользователя перед глазами без дополнительного скрола вниз, с чем столкнулась: 
<img width="733" alt="image" src="https://github.com/Medical-Information/medical-information-frontend/assets/76571113/73bf518b-fc8e-4669-bd23-4e1d307b24ee">

2023-08-10 03:12 UTC, elrouss commented
Посмотрю днем: не пулль, плиз.

Предлагаю еще добавить фичу запрета скролла окна тому, кто делает плавное открытие/закрытие (там нужно будет через `useEffect`)

2023-08-10 05:16 UTC, AleksandrDronov commented
> Логика фильтров в модальном окне отрабатывает как нужно: у меня получается увидеть результат фильтрации, а также сбросить фильтры при необходимости. Есть пара моментов, которые смущают, предлагаю над этим подумать и поправить функционал:
> 
> 1. Когда выбрали фильтры и переоткрыли модальное окно, ранее выбранные фильтры сбрасываются, хотя отфильтрованные данные мы по-прежнему видим по статьям. По идее, состояние выбранных фильтров должно сохраняться до тех пор, пока пользователь сам их не сбросит или не перезагрузит окно.
> 2. Если фильтры из модального окна должны дополнять фильтры из карусели, расширять поиск, то сейчас они друг друга перезатирают и результат получается либо по модальным фильтрам, либо карусель.
> 
> По стилям:
> 
> 1. Не хватает бордера в 1px над кнопками "показать" "очистить все":
> 
> <img alt="image" width="517" src="https://user-images.githubusercontent.com/76571113/259555205-e56d28e8-3304-4f06-bea2-d94c567725b6.png">
> 2. Очень не хватает плавного открытия и закрытия попапа
> 3. Предлагаю окно с фильтрами вытащить в центр экрана, чтобы оно всегда было у пользователя перед глазами без дополнительного скрола вниз, с чем столкнулась:
> 
> <img alt="image" width="733" src="https://user-images.githubusercontent.com/76571113/259561605-73bf518b-fc8e-4669-bd23-4e1d307b24ee.png">

Со всем согласен. Только п 3. Стилей. У меня окно спозиционировано в центре окна браузера. Не очень понимаю как у тебя получилось такое представление.

2023-08-10 09:22 UTC, elrouss requested changes
1) По макету в специализациях должно быть 10 ячеек; сейчас - 11 и поэтому не хватает места для текста последней;
2) Уточнить анимацию слайдера у дизайнеров: меня смущает, что слайдер движется на целый ряд вперед; логичнее было бы - на 1 ячейку, что помогло бы также избежать проблему, если ячеек нечетное количество (как это было по началу, когда у тебя шла прокрутка и половина второго ряда оказывалась пустой);
3) Нет счетчика фильтров;
4) Как верно заметила Полина, не сохраняется стейт выбранных фильтров. По идее, здесь нужно замемоизировать, чтобы фильтры не перерисовывались постоянно при открытии модального окна и монтировании компонента;
5) Как также заметила Полина, специализации и фильтры в связке не работают корректно;
6) И уточни все же у дизайнеров по "прыганью" верстки нижней секции, если не находятся статьи по выбранным фильм. Думаю, что они не предусмотрели это поведение и могли бы скорректировать высоту данного блока

2023-08-10 09:22 UTC, elrouss commented on src/services/features/filter/slice.tsx
> +    builder.addCase(getFilteredArticlesForModal.fulfilled, (state, action) => {
Не увидел редьюсеров для статусов `rejected` и `pending`: где в итоге обрабатывается выбрасываемая ошибка?

2023-08-10 09:22 UTC, elrouss commented on src/shared/checkboxes/filter-checkbox/filter-checkbox.tsx
> +        checked={isChecked}
Уверен? Если задавать жестко `checked`, потом не получится поменять статус

2023-08-10 11:01 UTC, AleksandrDronov commented
> 1. По макету в специализациях должно быть 10 ячеек; сейчас - 11 и поэтому не хватает места для текста последней;
> 2. Уточнить анимацию слайдера у дизайнеров: меня смущает, что слайдер движется на целый ряд вперед; логичнее было бы - на 1 ячейку, что помогло бы также избежать проблему, если ячеек нечетное количество (как это было по началу, когда у тебя шла прокрутка и половина второго ряда оказывалась пустой);
> 3. Нет счетчика фильтров;
> 4. Как верно заметила Полина, не сохраняется стейт выбранных фильтров. По идее, здесь нужно замемоизировать, чтобы фильтры не перерисовывались постоянно при открытии модального окна и монтировании компонента;
> 5. Как также заметила Полина, специализации и фильтры в связке не работают корректно;
> 6. И уточни все же у дизайнеров по "прыганью" верстки нижней секции, если не находятся статьи по выбранным фильм. Думаю, что они не предусмотрели это поведение и могли бы скорректировать высоту данного блока

1. Табы приходят с бека. Ширина таба определяется кол-вом символов специализации. Так что тут не угадаешь, какие будут специализации и сколько они займут места. Неизбежно перекрытие текста.
2. Пытался реализовать чтобы двигался один таб. Убил день. Оставил пока так. Нужно по-другому - третий релиз.
3. Сделал
4. Сделал
5. Сделал
6. Третий релиз.

2023-08-10 11:03 UTC, AleksandrDronov commented on src/services/features/filter/slice.tsx
> +    builder.addCase(getFilteredArticlesForModal.fulfilled, (state, action) => {
pending не нужен. rejected - добавлю потом, когда буду рефакторить код.

2023-08-10 11:03 UTC, AleksandrDronov commented on src/shared/checkboxes/filter-checkbox/filter-checkbox.tsx
> +        checked={isChecked}
уверен

2023-08-10 12:20 UTC, bofeof reviewed
Сейчас попап фильтры лучше дружат с каруселью, появился счетчик, состояние фильтров сохраняется после закрытия. Cтоит отметить, что хорошо сделан кейс: если сбросить фильтры с модалки, то фильтр карусели продолжает быть активным.
Что смущает: если в модалке оставить фильтры, но поменять секцию в карусели, то модалка сбрасывается, по моим ощущениям, так быть не должно, если мы уже фильтры выбрали

2023-08-10 12:20 UTC, bofeof commented on src/services/features/filter/slice.tsx
> +    builder.addCase(getFilteredArticlesForModal.fulfilled, (state, action) => {
Думаю, rejected стоит сейчас написать в слайсе, чтобы запрос был укоплектован, просто на уровне компонента, где вызывается запрос, пока не обрабатывать ошибку

2023-08-10 13:55 UTC, elrouss submitted a review, later dismissed
Стало определенно лучше, но еще есть, что доработать.

Полина верно заметила, что при нажатии "Сбросить фильтры" и просто закрытии модального окна без нажатия на "Показать" состояние сброшенных фильтров не сохраняется. Почему для сброса фильтров ты не пропишешь для кнопки тип `reset`? Обычно используют его в связке с чекбоксами, и логика стала бы значительно проще. Даже оставлял в самом у этой кнопки комментарий на данный счет :)

2023-08-10 14:29 UTC, AleksandrDronov commented
> Стало определенно лучше, но еще есть, что доработать.
> 
> Полина верно заметила, что при нажатии "Сбросить фильтры" и просто закрытии модального окна без нажатия на "Показать" состояние сброшенных фильтров не сохраняется. Почему для сброса фильтров ты не пропишешь для кнопки тип `reset`? Обычно используют его в связке с чекбоксами, и логика стала бы значительно проще. Даже оставлял в самом у этой кнопки комментарий на данный счет :)

Полина верно заметила, что при нажатии "Сбросить фильтры" и просто закрытии модального окна без нажатия на "Показать" состояние сброшенных фильтров не сохраняется. Специально так сделал, по мне если не применил фильтры, то их необходимо сбросить. Про reset зыбыл

2023-08-10 14:34 UTC, elrouss commented
Это не очевидно: я как пользователь при нажатии на сброс фильтров ожидаю, что фильтры сбросятся и мне не нужно никуда дополнительно нажимать. Тем более, что "Сбросить фильтры" и "Показать" разные вещи. Уточни у команды, какой должен быть сценарий у этой кнопки: те же самые тестировщики прицепятся.

По поводу слайдера в выбранной тобой библиотеке разве нельзя настраивать количество отображаемых элементов за раз на одном слайде? Обычно библиотеки предусматривают такую фичу

2023-08-10 14:35 UTC, elrouss commented
И зачем нам `cursor: pointer` на оверлее (это осталось от предыдущих людей, кто делал)?

2023-08-10 14:39 UTC, AleksandrDronov commented
> Это не очевидно: я как пользователь при нажатии на сброс фильтров ожидаю, что фильтры сбросятся и мне не нужно никуда дополнительно нажимать. Тем более, что "Сбросить фильтры" и "Показать" разные вещи. Уточни у команды, какой должен быть сценарий у этой кнопки: те же самые тестировщики прицепятся.
> 
> По поводу слайдера в выбранной тобой библиотеке разве нельзя настраивать количество отображаемых элементов за раз на одном слайде? Обычно библиотеки предусматривают такую фичу

Не понял, что не очевидно.

2023-08-10 15:53 UTC, bofeof approved these changes

2023-08-10 16:17 UTC, merged