feat: add sroll button
Medical-Information/medical-information-frontend pull request #180
Opened 2023-08-13 12:42 UTC by AleksandrDronov

Добавил на страницы новостей и статей кнопку скролла наверх.

2023-08-14 01:13 UTC, elrouss requested changes
Увы, надо поправить

2023-08-14 01:13 UTC, elrouss commented on src/pages/articles-preview-page/articles-preview-page.tsx
> +      document.body.scrollTop > 1400 ||
Вынести "магические" числа в переменные и написать в одну строчку:
`setIsButtonToTopVisible(document.body.scrollTop > 1400 || document.documentElement.scrollTop > 1400)`

2023-08-14 01:13 UTC, elrouss commented on src/pages/articles-preview-page/articles-preview-page.tsx
> +      document.body.scrollTop > 1400 ||
А вообще, уточнить у дизайнеров местоположение кнопки: по макету - она должна быть строго внизу, не раньше кнопки "еще", и, вероятно, всегда быть внизу экрана, а не повисать в воздухе, т.е. есть ей нужно задать `bottom: 0` и в принципе `useEffect` не требуется, т. к. она существует всегда внизу экрана
<img width="766" alt="Снимок экрана 2023-08-14 в 04 04 32" src="https://github.com/Medical-Information/medical-information-frontend/assets/108838349/6d264f08-63f2-4c23-b2bd-15f0e92056f5">

2023-08-14 01:13 UTC, elrouss commented on src/pages/news-preview-page/news-preview-page.module.scss
> +  right: 48px;
Вот что происходит на больших экранах, поскольку позиционирование у тебя выстроено относительно `window`
<img width="647" alt="Снимок экрана 2023-08-14 в 04 06 10" src="https://github.com/Medical-Information/medical-information-frontend/assets/108838349/7c172d07-904c-44b7-bc08-329e3189b98d">

Я бы сделал так: добавил на страницу дополнительную обертку (внутри нее - уже существующая обертка с галереей) и позиционировал кнопку уже относительно нее. Это бы также не заносило кнопку на галерею карточек при уменьшении разрешения экрана

2023-08-14 01:13 UTC, elrouss commented on src/pages/news-preview-page/news-preview-page.tsx
См. комментарии к блоку со статьями (все аналогично)

2023-08-14 05:45 UTC, AleksandrDronov commented on src/pages/news-preview-page/news-preview-page.module.scss
> +  right: 48px;
1. Если сделать bottom: 0, то кнопка будет в футере, что не соответствует макету.  
2. Это фиксированное позиоцинирование. Кнопка привязывается к окну браузера.  Выбрал именно такое, что кнопка висела всегда. Не понял про доп. контейнер. Какое позиционирование ты предлагаешь?

2023-08-14 11:11 UTC, AleksandrDronov commented
1. Уточнил у дизайнеров. Они хотят, чтобы кнопка была fixed. 
 2. Добавил функцию вычисления позиции кнопки в зависимости от ширины вьюпорта. Теперь на больших экранах не уезжает.

2023-08-14 17:07 UTC, elrouss commented
Не сказал бы, что формула правильная: `865px` - это слишком много, на адаптиве не будет работать. Работа с `vw` - не самое удачное решение, если у пользователя есть скроллбар (это ок. `17px`). Попробуй найти более гибкое решение
<img width="408" alt="Снимок экрана 2023-08-14 в 20 03 45" src="https://github.com/Medical-Information/medical-information-frontend/assets/108838349/73e8439a-3483-4724-989f-c425eb3b5488">

2023-08-14 17:08 UTC, elrouss commented on src/components/cards/article-preview/article-preview.module.scss
> +  width: 100%;
Эх, я уже добавил в коммите с head

2023-08-14 17:08 UTC, elrouss commented on src/services/features/information-material/slice.ts
> +      state.news.storage = action.payload.results.slice(0, 5);
Опять магическое значение: что за 5?

2023-08-14 18:39 UTC, AleksandrDronov commented
> Не сказал бы, что формула правильная: `865px` - это слишком много, на адаптиве не будет работать. Работа с `vw` - не самое удачное решение, если у пользователя есть скроллбар (это ок. `17px`). Попробуй найти более гибкое решение <img alt="Снимок экрана 2023-08-14 в 20 03 45" width="408" src="https://user-images.githubusercontent.com/108838349/260521232-73e8439a-3483-4724-989f-c425eb3b5488.png">

Сейчас у нас сайт не адаптивный и мы не разрабатываем адапитив в текущей реализации.

2023-08-14 19:01 UTC, elrouss commented
Заложить и предусмотреть на данном этапе уже адаптивность стоит -> смысл потом все переделывать?

2023-08-15 05:42 UTC, AleksandrDronov commented
> Заложить и предусмотреть на данном этапе уже адаптивность стоит -> смысл потом все переделывать?

Не понял, что ты написал

2023-08-15 05:44 UTC, elrouss approved these changes
В общем, забей. Видимо, пойдем по классической схеме: Борис переделает

2023-08-15 06:31 UTC, merged