Feat/comments
Medical-Information/medical-information-frontend pull request #187
Opened 2023-08-14 14:34 UTC by bofeof

2023-08-14 18:32 UTC, AleksandrDronov requested changes
Проделана большая работа. Логика работает точно. Ты молодец!

2023-08-14 18:32 UTC, AleksandrDronov commented on src/components/comments/comments.tsx
> +  const sendComment = async () => {
Ключевое слово async не нужно, посколько ты использовала промис и его методы, а не  await.
Сейчас вроде бы как в моде использовать async await. На твое усмотрение :)

2023-08-14 18:32 UTC, AleksandrDronov commented on src/components/comments/comments.tsx
> +          (res.payload as IComment) && (res.payload as IComment);
Не понял эту строку. Зачем дублирование?

2023-08-14 18:32 UTC, AleksandrDronov commented on src/components/comments/comments.tsx
> +            (comment) => resCommentId !== comment.id && { ...comment }
Конец строки `&& { ...comment }` не понял. Это часть не нужна. Если айди коммента в массиве не соответствует айди удаляему элементу, то элемент остается в массиве.

2023-08-14 18:32 UTC, AleksandrDronov commented on src/components/comments/comments.tsx
> +            (comment) => resCommentId !== comment.id && { ...comment }
Аналогично предедущему комментарию

2023-08-14 18:32 UTC, AleksandrDronov commented on src/components/header/index.tsx
> +    `${user?.first_name[0]} ${user?.last_name[0]}` || 'Дарья Врачева';
То есть если пользователь не залогинен, то 'Дарья Врачева'. Зачем?

2023-08-14 18:32 UTC, AleksandrDronov commented on src/components/news-preview-small/data/news.ts
Опять же. Если моковые данные не нужны, удаляем. Они могут быть нужны только для сторибука.

2023-08-14 18:32 UTC, AleksandrDronov commented on src/components/paper/data/data.ts
Опять же. Если моковые данные не нужны, удаляем. Они могут быть нужны только для сторибука.

2023-08-14 18:32 UTC, AleksandrDronov commented on src/components/user-profile-icon/index.tsx
>    const { user } = useAppSelector(showUserPersonalData);
Данный компонент низшего уровня. Не рекомендуется внутри него взаимодействоать со стейтом. 
Все данные должны приходить только через пропсы. В этом случае все просто. Я бы сделал один пропс user и передавал пользователя.

2023-08-14 18:32 UTC, AleksandrDronov commented on src/services/features/information-material/api.ts
> +    // getMaterialById: builder.query<TArticle, string | undefined>({
Если не нужно, то удаляем.

2023-08-14 18:32 UTC, AleksandrDronov commented on src/utils/types/article.tsx
> +    role: string;
Для роли лучше использовать литеральные типы

2023-08-15 05:37 UTC, bofeof commented on src/components/comments/comments.tsx
> +  const sendComment = async () => {
сначала без промисов писала, потом передумала, забыла убрать этот момент)

2023-08-15 05:37 UTC, bofeof commented on src/components/comments/comments.tsx
> +          (res.payload as IComment) && (res.payload as IComment);
в процессе работы меня тут почему-то типизация мучала и не пропускала, хотела сначала проверить так тип, что объект точно существует, потом его же и вернуть, упростила решение

2023-08-15 06:30 UTC, AleksandrDronov requested changes

2023-08-15 06:30 UTC, AleksandrDronov commented on src/components/articles-preview-small/articles-preview-small.stories.tsx
Почему сторю удалила?(  Из-за точно data удалила? Стори надо было оставить

2023-08-15 06:30 UTC, AleksandrDronov commented on src/components/news-preview-small/news-preview-small.stories.tsx
Почему сторю удалила?( Из-за точно data удалила? Стори надо было оставить

2023-08-15 06:30 UTC, AleksandrDronov commented on src/components/paper/paper.stories.tsx
Почему сторю удалила?( Из-за точно data удалила? Стори надо было оставить

2023-08-15 06:34 UTC, bofeof commented on src/components/articles-preview-small/articles-preview-small.stories.tsx
да, у меня все стори, которые удалены сейчас, с мок-данными связаны) а такие стори нужны были вообще? не самые переиспользуемые компоненты, чтобы их в сторибуке держать, показалось
я могу их вернуть, конечно

2023-08-15 06:37 UTC, AleksandrDronov commented on src/components/articles-preview-small/articles-preview-small.stories.tsx
Ну раз были, работа сделана. Жалко просто удалять. Верни плиз

2023-08-15 10:31 UTC, AleksandrDronov approved these changes

2023-08-15 10:31 UTC, merged