Forms validation
Medical-Information/medical-information-frontend pull request #217
Opened 2023-08-20 14:40 UTC by elrouss

Вроде бы все пофиксил -> проверяй. Один issue с формой авторизации остается пока открытым (задал туда вопрос), т. к. не понял, к чему в итоге пришли. Требуемый тестировщиками текст ошибок приходит с сервера и от нас не зависит

Попутно сделал плавной анимацию аватара в шапке (при наличии фото) и по запросу публики добавил паддинги в форме регистрации (проверь, пожалуйста, чтобы у тебя на мониторе не было белых полос)

2023-08-22 10:06 UTC, AleksandrDronov requested changes

2023-08-22 10:06 UTC, AleksandrDronov commented on src/pages/sign-up/sign-up.tsx
Проверить тексты ошибок не соотвествуют макету.
<img width="485" alt="Снимок экрана 2023-08-22 в 13 03 42" src="https://github.com/Medical-Information/medical-information-frontend/assets/93670312/4a12e45b-b2db-4db8-8ff6-dc70aa9603c9">

2023-08-22 10:08 UTC, elrouss commented on src/pages/reset-password-confirmation/reset-password-confirmation.tsx
Мы с Валерией это согласовали в пользу той формулировки, которая сейчас

2023-08-22 10:10 UTC, AleksandrDronov commented on src/pages/reset-password-confirmation/reset-password-confirmation.tsx
Ок, донеси эту инфу до дизайнеров. Надеюсь они согласовали данное изменение.

2023-08-22 10:10 UTC, elrouss commented on src/pages/sign-up/sign-up.tsx
Тексты ошибок взяты из требований. В случае с паролями я добавил только союз "и" между "минимум 6 максимум 20 символов" 

"Поля со звездочкой обязательны к заполнению" - договорились с дизайнерами и PM, что текст не будет подсвечиваться красным

2023-08-22 10:16 UTC, elrouss commented on src/pages/reset-password/reset-password.tsx
2 - думаю, что можно согласовать с PM, чтобы подправили формулировку в требованиях

2023-08-22 10:18 UTC, AleksandrDronov commented on src/pages/reset-password/reset-password.tsx
1. Галки явно не должно быть. 
2. Согласуй

2023-08-22 10:18 UTC, elrouss commented on src/pages/reset-password/reset-password.tsx
По п. 1.
Но тогда по-хорошему нужно и кнопку блокировать после неудачного ответа с сервера. Однако это уже отдельная логика

2023-08-22 10:19 UTC, elrouss commented on src/pages/reset-password/reset-password.tsx
Давай ты как тимлид согласуешь? Потому что я реально уже устал с этими формами. И обрати внимание на последний мой комментарий

2023-08-22 12:22 UTC, AleksandrDronov commented on src/pages/reset-password/reset-password.tsx
Тогда п 1, исправь. И кнопка должна быть заблокирована согласно макету и ТЗ

2023-08-22 12:27 UTC, AleksandrDronov commented on src/pages/reset-password/reset-password.tsx
<img width="907" alt="image" src="https://github.com/Medical-Information/medical-information-frontend/assets/93670312/47174d0c-4217-4c16-9f8d-8a974a932fdf">

2023-08-22 12:27 UTC, AleksandrDronov commented on src/pages/reset-password/reset-password.tsx
<img width="419" alt="image" src="https://github.com/Medical-Information/medical-information-frontend/assets/93670312/a3e458e4-c434-449e-8d15-71da4e75884b">

2023-08-22 12:28 UTC, elrouss commented on src/pages/reset-password/reset-password.tsx
Сделаю тогда, когда будет время.

2023-08-22 15:50 UTC, AleksandrDronov requested changes

2023-08-22 20:08 UTC, elrouss commented
Внес изменения в отрисовку ошибок после серверного ответа со статусом 4.. в соответствии с макетом

2023-08-23 07:48 UTC, AleksandrDronov approved these changes

2023-08-23 07:49 UTC, merged