feat(shared/buttons/button): create button with storybook
Medical-Information/medical-information-frontend pull request #23
Opened 2023-07-18 10:47 UTC by elrouss

2023-07-18 12:00 UTC, AleksandrDronov requested changes

2023-07-18 12:02 UTC, elrouss commented on src/shared/buttons/button/button.module.scss
> +@import '../../../assets/styles/abstracts/variables/fonts.scss';
У меня не работает `alias path`)

2023-07-18 12:05 UTC, elrouss commented on src/shared/buttons/button/button.stories.tsx
> +      defaultValue: 'Текст',
Изначально написал, но не увидел, чтобы оно появилось. Потом только дошло, что нужно смотреть во вкладке Docs)

В FavoriteButton уже описал)

2023-07-18 12:06 UTC, AleksandrDronov commented on src/shared/buttons/button/button.module.scss
> +@import '../../../assets/styles/abstracts/variables/fonts.scss';
у меня работает. Уверен?

2023-07-18 12:07 UTC, elrouss commented on src/shared/buttons/button/button.module.scss
> +@import '../../../assets/styles/abstracts/variables/fonts.scss';
Какой синтаксис?

В Next.js автоматически ставился @

2023-07-18 12:11 UTC, AleksandrDronov commented on src/shared/buttons/button/button.tsx
> +interface IButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
Но все же иметь возможность менять стили иногда очень нужна. Тут не знаю как лучше

2023-07-18 12:12 UTC, elrouss commented on src/shared/buttons/button/button.tsx
> +interface IButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
Почему просто не дописать тогда нужный стиль внутри самого компонента и активировать с помощью флага?

2023-07-18 12:17 UTC, elrouss commented on src/shared/buttons/button/button.tsx
> +interface IButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
Окей, тогда добавлю `extraClass`)

2023-07-19 05:39 UTC, elrouss commented
Отрефакторил кнопку, добавил избранное и фильтры (в сумме - 4)

2023-07-19 10:27 UTC, AleksandrDronov requested changes

2023-07-19 10:27 UTC, AleksandrDronov commented on src/shared/buttons/filter-button/filter-button.module.scss
Остался не проработанный вариант для "еще" [https://ibb.co/pvDz0nQ](https://ibb.co/pvDz0nQ). Необходимо уточнить у дизайнеров чем она отличается от обычного варианта. Или это не чекбокс а обычная кнопка?

2023-07-19 10:27 UTC, AleksandrDronov commented on src/shared/buttons/filter-tab/filter-tab.module.scss
Это все же не кнопка. Стоит переименовать в чекбокс и вынести в папку shared/checkboxes. Это касается всех файлов. Вопрос в названии чекбокс или таб открытый. Я склоняюсь за чекбокс, так как по факту это чекбокс.

2023-07-19 11:18 UTC, elrouss commented on src/shared/buttons/button/button.tsx
> +interface IButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
Клянусь, что было) бесит

2023-07-19 11:19 UTC, elrouss commented on src/assets/icons/components/dentistry.tsx
Я понимаю, но не могу ждать Александра, который уже 3 дня возится с иконками: там работы на пару часов максимум)

2023-07-19 11:20 UTC, elrouss commented on src/shared/buttons/favorite-button/favorite-button.tsx
> +  const iconBookmark = (
Я понимаю, но не могу ждать Александра, который уже 3 дня возится с иконками: там работы на пару часов максимум)

Тем более, что это кнопка избранных: здесь может быть только одна картинка

2023-07-19 11:21 UTC, elrouss commented on src/shared/buttons/filter-button/filter-button.module.scss
Это обычная кнопка типа `button secondary with border`

2023-07-19 11:23 UTC, elrouss commented on src/shared/buttons/button/button.stories.tsx
>  };
Размеры настраиваются через радио `small/medium`

2023-07-19 11:23 UTC, AleksandrDronov commented on src/shared/buttons/favorite-button/favorite-button.tsx
> +  const iconBookmark = (
Ну это на всякий, если вдруг появится такая же кнопка с другой иконкой. Иконку перенеси в сторю и там предай в компонент.

2023-07-19 11:25 UTC, AleksandrDronov commented on src/assets/icons/components/dentistry.tsx
То есть просто перенеси эту икону в сторю и передай в нужный компонент.

2023-07-19 11:29 UTC, elrouss commented on src/shared/buttons/filter-button/filter-button.module.scss
Визуально - кнопка, по функции - чекбокс) могу вынести, мне непринципиально))

2023-07-19 11:30 UTC, elrouss commented on src/shared/buttons/filter-tab/filter-tab.module.scss
Визуально - кнопка, по функции - чекбокс) могу вынести, мне непринципиально))

Оставить название таб, так как кнопки фильтрации - в модале)

2023-07-19 11:31 UTC, AleksandrDronov commented on src/shared/buttons/button/button.stories.tsx
>  };
Это понятно. Я про это - [https://ibb.co/gWNfWN0](https://ibb.co/gWNfWN0).

2023-07-19 11:32 UTC, AleksandrDronov commented on src/shared/buttons/filter-button/filter-button.module.scss
Выносим

2023-07-19 11:33 UTC, AleksandrDronov commented on src/shared/buttons/filter-tab/filter-tab.module.scss
выносим

2023-07-19 11:33 UTC, elrouss commented on src/shared/buttons/button/button.stories.tsx
>  };
Можно же просто на визуализации выбрать Secondary, проставить Small/Medium и готово без дублирования кода в stories)

Я же не выношу еще отдельно на каждую кнопку с border/не border

2023-07-19 11:34 UTC, elrouss commented on src/shared/buttons/favorite-button/favorite-button.tsx
> +  const iconBookmark = (
Тогда и назвать ее надо иначе

2023-07-19 11:39 UTC, AleksandrDronov commented on src/shared/buttons/button/button.stories.tsx
>  };
Это творческий вопрос конечно. Можно забить и вообще не делать эти состояния. А можно позаботиться о будущих тестировщиках и пользователей сторибука и сделать красиво.

2023-07-19 11:41 UTC, elrouss commented on src/shared/buttons/button/button.stories.tsx
>  };
Я предлагаю оставить так, как есть сейчас: работы куча и прорабатывать на данном этапе до мелочей все не получится (в понедельник - mvp))

2023-07-19 11:43 UTC, AleksandrDronov commented on src/shared/buttons/button/button.stories.tsx
>  };
Работы на 10 минут.

2023-07-19 11:54 UTC, elrouss commented on src/shared/buttons/button/button.module.scss
> +    background-color: $color-brand-primary-900;
Сделал, но рекомендую не тратить время на проверку цветов: это могут сделать и делают тестировщики (только если не должен быть красный, а я сделал зеленый))

2023-07-19 12:11 UTC, elrouss commented on src/shared/buttons/button/button.stories.tsx
>  };
Сделал, но код смотрится странно: куча дубля. Но тебе виднее

2023-07-19 12:17 UTC, AleksandrDronov approved these changes

2023-07-19 12:18 UTC, merged