feat(shared/checkboxes/consent-checkbox): create consent checkbox wit…
Medical-Information/medical-information-frontend pull request #27
Opened 2023-07-19 13:54 UTC by elrouss

…h storybook

2023-07-19 15:34 UTC, AleksandrDronov requested changes

2023-07-19 15:34 UTC, AleksandrDronov commented on src/shared/checkboxes/consent-checkbox/consent-checkbox.module.scss
> +      transition: $transition-button;
Давай уберем. Как-то криво с рывками происходит анимация.

2023-07-19 15:34 UTC, AleksandrDronov commented on src/shared/checkboxes/consent-checkbox/consent-checkbox.tsx
> +        defaultChecked={isChecked}
Тут нужно checked иначе не работает когда меняем пропс isChecked.

2023-07-19 15:39 UTC, elrouss commented on src/shared/checkboxes/consent-checkbox/consent-checkbox.module.scss
> +      transition: $transition-button;
Там в принципе не очень из-за того, что на hover дизайнеры увеличивают толщину border. Можем попросить их убрать толщину и тогда анимацию вроде норм

2023-07-19 15:40 UTC, elrouss commented on src/shared/checkboxes/consent-checkbox/consent-checkbox.tsx
> +        defaultChecked={isChecked}
В storybook не работает, а в верстке должно. Нужен именно default, иначе потом не получится его снимать

2023-07-19 15:41 UTC, AleksandrDronov commented on src/shared/checkboxes/consent-checkbox/consent-checkbox.module.scss
> +      transition: $transition-button;
да норм если эту строку убрать

2023-07-19 15:43 UTC, AleksandrDronov commented on src/shared/checkboxes/consent-checkbox/consent-checkbox.tsx
> +        defaultChecked={isChecked}
хмм. В другом проекте использовал checked. В сторибук должно также работать как и на сайте. На твое усмотрение.

2023-07-19 15:44 UTC, elrouss commented on src/shared/checkboxes/consent-checkbox/consent-checkbox.tsx
> +        defaultChecked={isChecked}
Я использовал default) можем сделать под story, но я оставлю тогда коммент

2023-07-19 15:45 UTC, AleksandrDronov commented on src/shared/checkboxes/consent-checkbox/consent-checkbox.tsx
> +        defaultChecked={isChecked}
если что изменим конечно

2023-07-19 22:35 UTC, elrouss commented on src/shared/checkboxes/consent-checkbox/consent-checkbox.tsx
> +        defaultChecked={isChecked}
Как я и говорил, при установке `checked` вместо `defaultChecked` невозможно переключать инпут, в том числе в Storybook: он хардкодится. Поэтому не меняю

2023-07-20 08:40 UTC, AleksandrDronov approved these changes

2023-07-20 08:40 UTC, merged