feat: создал иконки и добавил их в storybook
Medical-Information/medical-information-frontend pull request #30
Opened 2023-07-19 22:49 UTC by shuraaas

Вродь все сделал, принимаю замечания)

2023-07-20 10:00 UTC, AleksandrDronov requested changes
Необходимо выполнить вторую часть таски. Добавить в сторибук. Посмотри предложенный референс.

2023-07-20 10:51 UTC, AleksandrDronov requested changes

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/all-icon.tsx
> +import React from 'react';
Удалить лишний импорт во всех файлах.

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/utils.tsx
> +      return '#666372';
В макете цвет - #838090

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/big-arrow-icon.tsx
В сторибуке не отбображается иконка.

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/cloud-drizzel-icon.tsx
Отображается некорректно. [https://ibb.co/hW8qCY4](https://ibb.co/hW8qCY4)

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/cloud-drizzel-one-icon.tsx
Отображается некорректно.

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/cloud-icon.tsx
Отображается некорректно.

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/clouds-icon.tsx
Отображается некорректно.

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/cold-temperature-icon.tsx
Отображается некорректно.

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/cold-weather-icon.tsx
Отображается некорректно.

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/cold-weather-two-icon.tsx
Отображается некорректно.

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/cold-weather-one-icon.tsx
Отображается некорректно.

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/dentistry-icon.tsx
Зуб должен быть внутри без заливки.

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/desert-icon.tsx
Отображается некорректно.

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/direction-tool-icon.tsx
Отображается некорректно.

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/eclipsed-icon.tsx
Отображается некорректно.

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/eye-closed-icon.tsx
Без заливки

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/filters-icon.tsx
Без заливки внутри

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/hail-during-night-icon.tsx
Некорретно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/hail-icon.tsx
Некорретно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/high-temperature-icon.tsx
Некорретно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/high-temperature-one-icon.tsx
Некорретно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/bookmark-fill-icon.tsx
не та иконка

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/location-pin-icon.tsx
некорректно экспортирована (маленькая)

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/mail-icon.tsx
Не должно быть заливки

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/moon-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/moon-with-wind-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/moonset-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/night-weather-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/not-available-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/ocean-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/podcast-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/rain-one-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/rain-two-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/rain-three-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/rain-four-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/rain-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/rainbow-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/rainy-weather-five-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/rainy-weather-four-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/rainy-weather-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/rainy-weather-one-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/rainy-weather-seven-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/rainy-weather-six-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/rainy-weather-three-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/rainy-weather-two-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/scenery-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/snowflake-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/snowflake-one-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/storm-weather-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/storm-weather-one-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/storm-weather-two-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/sun-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/sun-with-wind-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/sunset-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/user-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/vk-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/warm-weather-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/water-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/wind-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/wind-one-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/windy-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/youtube-icon.tsx
Некорректно отображается

2023-07-20 10:51 UTC, AleksandrDronov commented on src/shared/icons/zen-icon.tsx
Некорректно отображается

2023-07-21 10:54 UTC, shuraaas commented
@AleksandrDronov все готово!

2023-07-21 12:17 UTC, AleksandrDronov approved these changes
Всё супер. Спасибо

2023-07-21 12:17 UTC, merged